package mapping;
// Generated 3/07/2014 10:22:26 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Obervaciones generated by hbm2java
 */
@Entity
@Table(name="obervaciones"
    ,catalog="essy_ave"
)
public class Obervaciones  implements java.io.Serializable {


     private Integer idObervaciones;
     private String razon;
     private Date registro;
     private String idusuario;

    public Obervaciones() {
    }

	
    public Obervaciones(String idusuario) {
        this.idusuario = idusuario;
    }
    public Obervaciones(String razon, Date registro, String idusuario) {
       this.razon = razon;
       this.registro = registro;
       this.idusuario = idusuario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idObervaciones", unique=true, nullable=false)
    public Integer getIdObervaciones() {
        return this.idObervaciones;
    }
    
    public void setIdObervaciones(Integer idObervaciones) {
        this.idObervaciones = idObervaciones;
    }
    
    @Column(name="razon", length=65535)
    public String getRazon() {
        return this.razon;
    }
    
    public void setRazon(String razon) {
        this.razon = razon;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registro", length=19)
    public Date getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Date registro) {
        this.registro = registro;
    }
    
    @Column(name="idusuario", nullable=false, length=100)
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }




}


