package mapping;
// Generated 3/07/2014 10:22:26 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "essy_ave")
public class Usuario implements java.io.Serializable {

    private String idusuario;
    private String clave;
    private String mail;
    private String nombre;
    private String apellido;
    private int permiso;
    private int estado;

    public Usuario() {
    }

    public Usuario(String idusuario) {
        this.idusuario = idusuario;
    }

    public Usuario(String idusuario, String clave, String mail, String nombre, String apellido, int permiso, int estado) {
        this.idusuario = idusuario;
        this.clave = clave;
        this.mail = mail;
        this.nombre = nombre;
        this.apellido = apellido;
        this.permiso = permiso;
        this.estado = estado;
    }

    @Id
    @Column(name = "idusuario", unique = true, nullable = false, length = 100)
    public String getIdusuario() {
        return this.idusuario;
    }

    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }

    @Column(name = "clave", length = 500)
    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    @Column(name = "permiso")
    public int getPermiso() {
        return permiso;
    }

    public void setPermiso(int permiso) {
        this.permiso = permiso;
    }

    @Column(name = "estado")
    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    @Column(name = "mail", length = 200)
    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @Column(name = "nombre", length = 200)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "apellido", length = 200)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
}
