package mapping;
// Generated 31/03/2017 07:42:52 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="essy_ave"
)
public class Usuario  implements java.io.Serializable {


     private String idusuario;
     private String clave;
     private String mail;
     private String nombre;
     private String apellido;
     private int permiso;
     private int estado;

    public Usuario() {
    }

	
    public Usuario(String idusuario, int permiso, int estado) {
        this.idusuario = idusuario;
        this.permiso = permiso;
        this.estado = estado;
    }
    public Usuario(String idusuario, String clave, String mail, String nombre, String apellido, int permiso, int estado) {
       this.idusuario = idusuario;
       this.clave = clave;
       this.mail = mail;
       this.nombre = nombre;
       this.apellido = apellido;
       this.permiso = permiso;
       this.estado = estado;
    }
   
     @Id 
    
    @Column(name="idusuario", unique=true, nullable=false, length=100)
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }
    
    @Column(name="clave", length=500)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="mail", length=200)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    
    @Column(name="nombre", length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="apellido", length=200)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    
    @Column(name="permiso", nullable=false)
    public int getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(int permiso) {
        this.permiso = permiso;
    }
    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


